# Generated by Django 4.1 on 2024-03-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0005_alter_eptrack_release_date_alter_single_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eptrack',
            name='album_art',
            field=models.ImageField(blank=True, default='album_art/default-cover-art.png', null=True, upload_to='album_art/'),
        ),
        migrations.AddField(
            model_name='single',
            name='album_art',
            field=models.ImageField(blank=True, default='album_art/default-cover-art.png', null=True, upload_to='album_art/'),
        ),
        migrations.AddField(
            model_name='song',
            name='album_art',
            field=models.ImageField(blank=True, default='album_art/default-cover-art.png', null=True, upload_to='album_art/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ep',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
