# Generated by Django 4.1 on 2024-03-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_art',
            field=models.ImageField(blank=True, null=True, upload_to='album_art/'),
        ),
        migrations.AddField(
            model_name='ep',
            name='album_art',
            field=models.ImageField(blank=True, null=True, upload_to='album_art/'),
        ),
    ]
