# Generated by Django 4.1 on 2024-03-13 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0002_album_album_art_ep_album_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicreview',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
