# Generated by Django 4.1 on 2024-03-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0003_musicreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.ImageField(blank=True, default='album_art/default-cover-art.png', null=True, upload_to='album_art/'),
        ),
        migrations.AlterField(
            model_name='ep',
            name='album_art',
            field=models.ImageField(blank=True, default='album_art/default-cover-art.png', null=True, upload_to='album_art/'),
        ),
    ]
