# Generated by Django 4.1 on 2024-03-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('review_site', '0007_album_content_type_ep_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
